import { PT_Sans } from "next/font/google";
import "./globals.scss";
import Navbar from "./components/navbar";

const pt_sans = PT_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={pt_sans.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
